When text is wrapped in pdf file, pdftotext outputs '\n' which makes it difficult to assertIn the expected text.  Consider this as an example of the problem:
  AssertionError: 'video dimensions changing, font size changing and table
  border creation' not found in "5\n\nExample Co., Ltd.\nCompany
  Registration No.: 010-101-010-010-1\n00/11 Example Road, Example,
  Example, Bangkok 10100\nTel: +66-2-010-0101 Fax:
  +66-2-010-0101\n\nInvoice\n\nCustomer's Name & Address\n\n26. Apr.
  2017\n\nTesttorimo Co., Ltd.\n\nNo.: 966\n\n17/1 Testing Road, Testing
  Lane, Bangkok, 10100\n\nBy: Ms Example Example\n\nCompany Registration
  No.: 0-0000-00000-00-0\n\nDescription\n\nPrice (THB)\n\nvideo dimensions
  changing, font size changing and table
  border\ncreation\n\n1,800.00\n\nVAT 7%\n\n126.00\n\nHow To Pay\n\nW/T
  3%\n\n54.00\n\nBank Transfer\n\nTotal\n\n1,872.00\n\nK-Bank, Example
  Co., Ltd., Account No.: 010-010-0101\nSWIFT CODE: KASITHBK\nBank
  Address: K-Bank\nExample Branch\n010 Example Road, Example, Bangkok
  10100\n\n\x0c"

Notice the '\n' between 'border' and 'creation'.